import { StyleSheet } from "react-native";

import { theme } from "../../../theme";

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  scrollContent: {
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
    paddingBottom: theme.spacing.xxl,
  },
  listHeader: {
    gap: theme.spacing.md,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceAlt,
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  brand: {
    color: theme.colors.primary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  headerTitle: {
    color: theme.colors.text,
    fontSize: 22,
    fontWeight: "700",
  },
  headerSubtitle: {
    color: theme.colors.mutedText,
    fontSize: 13,
    lineHeight: 18,
  },
  moduleSwitcher: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    paddingVertical: theme.spacing.sm,
  },
  moduleSwitcherContent: {
    gap: theme.spacing.sm,
    paddingHorizontal: theme.spacing.lg,
  },
  moduleSwitchChip: {
    minHeight: 36,
    justifyContent: "center",
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceAlt,
    paddingHorizontal: theme.spacing.lg,
  },
  moduleSwitchChipSelected: {
    backgroundColor: theme.colors.primary,
  },
  moduleSwitchChipContent: {
    maxWidth: 160,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.xs,
  },
  moduleSwitchText: {
    flexShrink: 1,
    color: theme.colors.mutedText,
    fontSize: 12,
    fontWeight: "700",
  },
  moduleSwitchTextSelected: {
    color: theme.colors.onPrimary,
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  searchInput: {
    flex: 1,
    minHeight: 44,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.surfaceAlt,
    color: theme.colors.text,
    fontSize: 16,
    paddingHorizontal: theme.spacing.md,
  },
  primaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.primary,
    paddingHorizontal: theme.spacing.lg,
  },
  dangerButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.dangerSoft,
    paddingHorizontal: theme.spacing.lg,
  },
  mutedButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceAlt,
    paddingHorizontal: theme.spacing.lg,
  },
  primaryButtonText: {
    color: theme.colors.onPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  mutedButtonText: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: "600",
  },
  dangerButtonText: {
    color: theme.colors.danger,
    fontSize: 16,
    fontWeight: "600",
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.sm,
  },
  chip: {
    minHeight: 36,
    justifyContent: "center",
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceAlt,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.xs,
  },
  chipSelected: {
    backgroundColor: theme.colors.primary,
  },
  chipText: {
    color: theme.colors.mutedText,
    fontSize: 13,
    fontWeight: "600",
  },
  chipTextSelected: {
    color: theme.colors.onPrimary,
  },
  recordCard: {
    gap: theme.spacing.sm,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.lg,
    ...theme.shadows.sm,
  },
  entityHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
  },
  entityAvatar: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 24,
    backgroundColor: theme.colors.primarySoft,
  },
  entityAvatarText: {
    color: theme.colors.primaryDark,
    fontSize: 14,
    fontWeight: "700",
  },
  entityText: {
    flex: 1,
    minWidth: 0,
    gap: theme.spacing.xs,
  },
  vehicleRecordCard: {
    gap: theme.spacing.md,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.lg,
    ...theme.shadows.sm,
  },
  vehicleMediaRow: {
    flexDirection: "row",
    gap: theme.spacing.md,
  },
  vehicleThumb: {
    width: 82,
    height: 82,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.hero,
  },
  vehicleThumbImage: {
    width: "100%",
    height: "100%",
  },
  vehicleThumbText: {
    color: theme.colors.onPrimary,
    fontSize: 22,
    fontWeight: "700",
  },
  vehicleCardText: {
    flex: 1,
    minWidth: 0,
    gap: theme.spacing.sm,
  },
  vehicleFactRow: {
    gap: theme.spacing.xs,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.surfaceAlt,
    padding: theme.spacing.sm,
  },
  recordHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing.md,
  },
  recordTitle: {
    flex: 1,
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: "700",
  },
  recordMeta: {
    color: theme.colors.mutedText,
    fontSize: 13,
    lineHeight: 19,
  },
  statusPill: {
    overflow: "hidden",
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceAlt,
    color: theme.colors.mutedText,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.3,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
  },
  detailPillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.xs,
  },
  detailPill: {
    minHeight: 28,
    justifyContent: "center",
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceAlt,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
  },
  detailPillSuccess: {
    backgroundColor: theme.colors.successSoft,
  },
  detailPillWarning: {
    backgroundColor: theme.colors.warningSoft,
  },
  detailPillInfo: {
    backgroundColor: theme.colors.infoSoft,
  },
  detailPillText: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: "700",
  },
  cardActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.sm,
  },
  warningText: {
    color: theme.colors.accent,
    fontSize: 13,
    fontWeight: "600",
  },
  inlineActionGroup: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: theme.spacing.sm,
  },
  inlineActionField: {
    flex: 1,
    minWidth: 0,
  },
  formField: {
    gap: theme.spacing.xs,
  },
  formLabel: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  formInput: {
    minHeight: 48,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.surfaceAlt,
    color: theme.colors.text,
    fontSize: 16,
    paddingHorizontal: theme.spacing.md,
  },
  formInputMultiline: {
    minHeight: 96,
    paddingTop: theme.spacing.md,
  },
  modalRoot: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15,23,42,0.42)",
  },
  modalSheet: {
    maxHeight: "88%",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: theme.colors.background,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
    padding: theme.spacing.md,
  },
  modalTitle: {
    flex: 1,
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: "700",
  },
  modalContent: {
    gap: theme.spacing.md,
    padding: theme.spacing.md,
    paddingBottom: theme.spacing.xxl,
  },
  emptyState: {
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.xl,
    ...theme.shadows.sm,
  },
  emptyText: {
    color: theme.colors.mutedText,
    fontSize: 14,
    textAlign: "center",
  },
  summaryPanel: {
    gap: theme.spacing.md,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.lg,
    ...theme.shadows.sm,
  },
  summaryHeader: {
    gap: theme.spacing.xs,
  },
  summaryTitle: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: "700",
  },
  summarySubtitle: {
    color: theme.colors.mutedText,
    fontSize: 12,
    lineHeight: 18,
  },
  summaryRows: {
    gap: theme.spacing.sm,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: theme.spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.border,
    paddingTop: theme.spacing.sm,
  },
  summaryLabel: {
    flex: 0.44,
    color: theme.colors.mutedText,
    fontSize: 12,
    fontWeight: "600",
  },
  summaryValue: {
    flex: 0.56,
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "right",
  },
  wizardActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  wizardPrimaryAction: {
    flex: 1,
  },
  mutedText: {
    color: theme.colors.mutedText,
    fontSize: 14,
    textAlign: "center",
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.md,
  },
  metricCard: {
    width: "47.8%",
    minHeight: 118,
    justifyContent: "space-between",
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.lg,
    ...theme.shadows.sm,
  },
  metricTitle: {
    color: theme.colors.mutedText,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  metricValue: {
    color: theme.colors.text,
    fontSize: 28,
    fontWeight: "700",
    letterSpacing: -0.5,
  },
  metricCaption: {
    color: theme.colors.mutedText,
    fontSize: 12,
    fontWeight: "700",
  },
  sectionTitle: {
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: "700",
  },
  permissionRow: {
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.sm,
  },
  permissionText: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: "700",
  },
  swatchRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.sm,
  },
  swatchButton: {
    width: "48%",
    gap: theme.spacing.sm,
    borderRadius: theme.radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.sm,
  },
  swatchSelected: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primarySoft,
  },
  swatchStack: {
    height: 38,
    overflow: "hidden",
    flexDirection: "row",
    borderRadius: theme.radius.sm,
  },
  swatchFill: {
    flex: 1,
  },
  swatchLabel: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: "700",
  },
  websitePreview: {
    minHeight: 190,
    overflow: "hidden",
    justifyContent: "flex-end",
    gap: theme.spacing.sm,
    borderRadius: theme.radius.md,
    padding: theme.spacing.lg,
  },
  websitePreviewBadge: {
    alignSelf: "flex-start",
    overflow: "hidden",
    borderRadius: theme.radius.sm,
    backgroundColor: "rgba(255,255,255,0.18)",
    color: theme.colors.onPrimary,
    fontSize: 11,
    fontWeight: "700",
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  websitePreviewTitle: {
    color: theme.colors.onPrimary,
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 32,
  },
  websitePreviewSubtitle: {
    color: theme.colors.onPrimary,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
    opacity: 0.88,
  },
  websitePreviewAccent: {
    height: 5,
    width: 96,
    borderRadius: theme.radius.sm,
  },
  messagesRoot: {
    flex: 1,
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
  },
  messagesToolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  messagesLayout: {
    flex: 1,
    gap: theme.spacing.md,
  },
  conversationList: {
    maxHeight: 208,
  },
  conversationListContent: {
    gap: theme.spacing.sm,
  },
  conversationCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.md,
    ...theme.shadows.sm,
  },
  conversationCardActive: {
    backgroundColor: theme.colors.primarySoft,
  },
  conversationAvatar: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    backgroundColor: theme.colors.surfaceAlt,
  },
  conversationAvatarText: {
    color: theme.colors.primary,
    fontSize: 13,
    fontWeight: "700",
  },
  unreadDot: {
    position: "absolute",
    top: 1,
    right: 1,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.colors.primary,
  },
  conversationText: {
    flex: 1,
    minWidth: 0,
    gap: theme.spacing.xs,
  },
  conversationTitle: {
    flex: 1,
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: "700",
  },
  conversationTime: {
    color: theme.colors.mutedText,
    fontSize: 11,
    fontWeight: "600",
  },
  conversationPreview: {
    color: theme.colors.mutedText,
    fontSize: 12,
    lineHeight: 17,
  },
  conversationUnread: {
    color: theme.colors.text,
    fontWeight: "700",
  },
  threadPanel: {
    flex: 1,
    overflow: "hidden",
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    ...theme.shadows.sm,
  },
  threadHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
    padding: theme.spacing.md,
  },
  threadTitle: {
    color: theme.colors.text,
    fontSize: 17,
    fontWeight: "700",
  },
  threadScroll: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  threadContent: {
    gap: theme.spacing.sm,
    padding: theme.spacing.md,
  },
  messageRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  messageRowMine: {
    justifyContent: "flex-end",
  },
  messageBubble: {
    maxWidth: "84%",
    gap: theme.spacing.xs,
    borderRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  messageBubbleOther: {
    backgroundColor: theme.colors.surfaceAlt,
  },
  messageBubbleMine: {
    backgroundColor: theme.colors.primary,
  },
  messageSender: {
    color: theme.colors.primary,
    fontSize: 11,
    fontWeight: "700",
  },
  messageBody: {
    color: theme.colors.text,
    fontSize: 15,
    lineHeight: 21,
  },
  messageBodyMine: {
    color: theme.colors.onPrimary,
  },
  messageMeta: {
    color: theme.colors.mutedText,
    fontSize: 10,
    fontWeight: "600",
  },
  messageMetaMine: {
    color: theme.colors.primarySoft,
  },
  typingText: {
    color: theme.colors.mutedText,
    fontSize: 12,
    fontStyle: "italic",
  },
  composerRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: theme.spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.border,
    padding: theme.spacing.md,
  },
  composerInput: {
    flex: 1,
    minHeight: 46,
    maxHeight: 112,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surfaceAlt,
    color: theme.colors.text,
    fontSize: 16,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
  },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.md,
    ...theme.shadows.sm,
  },
  memberRowSelected: {
    backgroundColor: theme.colors.primarySoft,
  },
  memberAvatar: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: theme.colors.surfaceAlt,
  },
  memberAvatarText: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: "700",
  },
  unavailable: {
    flex: 1,
    justifyContent: "center",
    gap: theme.spacing.md,
    padding: theme.spacing.xl,
  },
  errorTitle: {
    color: theme.colors.text,
    fontSize: 22,
    fontWeight: "700",
    textAlign: "center",
  },
  errorBody: {
    color: theme.colors.mutedText,
    fontSize: 15,
    textAlign: "center",
  },
  disabled: {
    opacity: 0.5,
  },
  pressed: {
    opacity: 0.82,
  },
});

