name = "autoflow-dealer-sites"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "*.autoflowdealer.com/*", zone_name = "autoflowdealer.com" }
]
