import { ConvexError } from "convex/values";

export const AppErrorCode = {
  // Auth
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  // Not found
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  SALE_NOT_FOUND: "SALE_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  LEAD_NOT_FOUND: "LEAD_NOT_FOUND",
  QUOTE_NOT_FOUND: "QUOTE_NOT_FOUND",
  EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  DEPOSIT_NOT_FOUND: "DEPOSIT_NOT_FOUND",
  // Business logic
  DEPOSIT_ALREADY_RESOLVED: "DEPOSIT_ALREADY_RESOLVED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VEHICLE_ALREADY_SOLD: "VEHICLE_ALREADY_SOLD",
  VEHICLE_ARCHIVED: "VEHICLE_ARCHIVED",
  SALESPERSON_NOT_MEMBER: "SALESPERSON_NOT_MEMBER",
  ASSIGNED_USER_NOT_MEMBER: "ASSIGNED_USER_NOT_MEMBER",
  SALE_ALREADY_COMPLETED: "SALE_ALREADY_COMPLETED",
  SALE_ALREADY_CANCELLED: "SALE_ALREADY_CANCELLED",
  PENDING_REQUEST_EXISTS: "PENDING_REQUEST_EXISTS",
  REQUEST_ALREADY_RESOLVED: "REQUEST_ALREADY_RESOLVED",
  OWNER_ROLE_LOCKED: "OWNER_ROLE_LOCKED",
  ROLE_IN_USE: "ROLE_IN_USE",
  ALREADY_MEMBER: "ALREADY_MEMBER",
  ALREADY_ADMIN: "ALREADY_ADMIN",
  CANNOT_REMOVE_OWNER: "CANNOT_REMOVE_OWNER",
  CANNOT_CHANGE_OWNER_ROLE: "CANNOT_CHANGE_OWNER_ROLE",
  // SCRUM-51. Claims is retired as an accounting authority; its five
  // writers refuse rather than open a second finance-company receivable.
  CLAIMS_RETIRED: "CLAIMS_RETIRED",
  // SCRUM-495. LEASE and INTERNAL_INSTALLMENT are no longer offered; every door
  // that would create or finalize a deal in one refuses with this code.
  DEAL_MODE_RETIRED: "DEAL_MODE_RETIRED",
  // SCRUM-504. A financed sale exists only through the Deal (`applications.finalizeDeal`),
  // which carries the finance application; a sale door that names FINANCED without one refuses.
  FINANCED_SALE_REQUIRES_DEAL: "FINANCED_SALE_REQUIRES_DEAL",
  // SCRUM-69 / SCRUM-532. A car held by a finance application in flight is sold only through
  // `applications.finalizeDeal` for that application; every other completion door refuses.
  SALE_COMPLETES_THROUGH_FINANCE_APPLICATION: "SALE_COMPLETES_THROUGH_FINANCE_APPLICATION",
  // SCRUM-528. `finalizeDeal` builds the sale only from quote economics that still agree with
  // the pricing frozen on the finance application; a disagreement refuses before any write.
  QUOTE_ECONOMICS_DRIFTED: "QUOTE_ECONOMICS_DRIFTED",
  // SCRUM-239. Returning a cleared finance-company cheque from the deal; each
  // refusal is raised before the first write and is translated under
  // ServerError_<code>.
  FINANCE_RETURN_NOT_DISBURSED: "FINANCE_RETURN_NOT_DISBURSED",
  FINANCE_RETURN_CHEQUE_NOT_CLEARED: "FINANCE_RETURN_CHEQUE_NOT_CLEARED",
  FINANCE_RETURN_CHAIN_MISMATCH: "FINANCE_RETURN_CHAIN_MISMATCH",
  FINANCE_RETURN_ALLOCATION_SHAPE: "FINANCE_RETURN_ALLOCATION_SHAPE",
  FINANCE_RETURN_REVERSAL_UNPROVEN: "FINANCE_RETURN_REVERSAL_UNPROVEN",
  FINANCE_RETURN_REASON_REQUIRED: "FINANCE_RETURN_REASON_REQUIRED",
  FINANCE_RETURN_REASON_TOO_LONG: "FINANCE_RETURN_REASON_TOO_LONG",
  FINANCE_CHEQUE_RETURN_FROM_DEAL: "FINANCE_CHEQUE_RETURN_FROM_DEAL",
  // SCRUM-239 follow-up. One code for a missing and a foreign-organisation row,
  // so the refusal never discloses that another tenant's row exists.
  FINANCE_RETURN_NOT_FOUND: "FINANCE_RETURN_NOT_FOUND",
  FINANCE_RETURN_KEY_CONFLICT: "FINANCE_RETURN_KEY_CONFLICT",
  // `collections.returnCheque`: RETURNED is terminal for returning.
  CHEQUE_ALREADY_RETURNED: "CHEQUE_ALREADY_RETURNED",
  CHEQUE_NOT_RETURNABLE: "CHEQUE_NOT_RETURNABLE",
  CHEQUE_NOT_FOUND: "CHEQUE_NOT_FOUND",
  // SCRUM-239 round 2.
  CHEQUE_NOT_CLEARED: "CHEQUE_NOT_CLEARED",
  FINANCE_RETURN_KEY_INVALID: "FINANCE_RETURN_KEY_INVALID",
  FINANCE_CONFIRM_STALE_REQUEST: "FINANCE_CONFIRM_STALE_REQUEST",
  // SCRUM-239 round 3.
  FINANCE_CONFIRM_ALREADY_CONFIRMED: "FINANCE_CONFIRM_ALREADY_CONFIRMED",
  FINANCE_CONFIRM_CHEQUE_ALREADY_CLEARED: "FINANCE_CONFIRM_CHEQUE_ALREADY_CLEARED",
  FINANCE_CONFIRM_CHEQUE_RETURNED_OR_CANCELLED: "FINANCE_CONFIRM_CHEQUE_RETURNED_OR_CANCELLED",
  FINANCE_CONFIRM_CHEQUE_NOT_FOUND: "FINANCE_CONFIRM_CHEQUE_NOT_FOUND",
  FINANCE_CONFIRM_MULTIPLE_LIVE_CHEQUES: "FINANCE_CONFIRM_MULTIPLE_LIVE_CHEQUES",
  FINANCE_CONFIRM_CHEQUE_FACE_UNRECORDED: "FINANCE_CONFIRM_CHEQUE_FACE_UNRECORDED",
  FINANCE_CONFIRM_CHEQUE_FACE_MISMATCH: "FINANCE_CONFIRM_CHEQUE_FACE_MISMATCH",
  FINANCE_CONFIRM_NO_FINANCIER_PAYS: "FINANCE_CONFIRM_NO_FINANCIER_PAYS",
  FINANCE_CONFIRM_NO_FINANCE_COMPANY: "FINANCE_CONFIRM_NO_FINANCE_COMPANY",
  CHEQUE_BANK_FEE_INVALID: "CHEQUE_BANK_FEE_INVALID",
  CHEQUE_RETURN_NO_RECEIPT_LINEAGE: "CHEQUE_RETURN_NO_RECEIPT_LINEAGE",
  CHEQUE_RETURN_NO_PAYMENT_TO_REVERSE: "CHEQUE_RETURN_NO_PAYMENT_TO_REVERSE",
  // SCRUM-239 round 4: `collections.returnClearedCheque` key reuse with a different
  // cheque, reason or bank fee (its fingerprint includes the fee).
  CHEQUE_RETURN_KEY_CONFLICT: "CHEQUE_RETURN_KEY_CONFLICT",
  // SCRUM-542. `fixedAssets.impair` / `fixedAssets.dispose` accounting-date guards, each raised
  // before the first write and translated under ServerError_<code>.
  ASSET_EVENT_DATE_INVALID: "ASSET_EVENT_DATE_INVALID",
  ASSET_EVENT_DATE_IN_FUTURE: "ASSET_EVENT_DATE_IN_FUTURE",
  ASSET_EVENT_BEFORE_CAPITALIZATION: "ASSET_EVENT_BEFORE_CAPITALIZATION",
  ASSET_EVENT_BEFORE_DEPRECIATION: "ASSET_EVENT_BEFORE_DEPRECIATION",
  ASSET_EVENT_BEFORE_IMPAIRMENT: "ASSET_EVENT_BEFORE_IMPAIRMENT",
  ASSET_PURCHASE_DATE_IN_FUTURE: "ASSET_PURCHASE_DATE_IN_FUTURE",
  ASSET_PURCHASE_DATE_INVALID: "ASSET_PURCHASE_DATE_INVALID",
  ASSET_DEPRECIATION_START_DATE_INVALID: "ASSET_DEPRECIATION_START_DATE_INVALID",
  // SCRUM-563. Post-reset safety. A command identity recorded before an org financial reset
  // cannot replay after it; the org cannot be reactivated mid-reset. Translated under
  // ServerError_<code>.
  COMMAND_RECORDED_BEFORE_RESET: "COMMAND_RECORDED_BEFORE_RESET",
  ORG_FINANCIAL_RESET_IN_PROGRESS: "ORG_FINANCIAL_RESET_IN_PROGRESS",
} as const;

export type AppErrorCode = typeof AppErrorCode[keyof typeof AppErrorCode];

/**
 * The one structured `ConvexError` payload: a machine code plus the English
 * message `lib/errors.ts` `getErrorMessage` shows. A domain with its own code
 * vocabulary (e.g. the closing-readiness reasons, SCRUM-414) widens `C`
 * rather than defining another shape.
 */
export type AppErrorData<C extends string = AppErrorCode> = {
  code: C;
  message: string;
};

export function throwAppError(code: AppErrorCode, message: string): never {
  throw new ConvexError({ code, message });
}
