import { ConvexError } from "convex/values";

export const AppErrorCode = {
  // Auth
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  // Not found
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  SALE_NOT_FOUND: "SALE_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  LEAD_NOT_FOUND: "LEAD_NOT_FOUND",
  QUOTE_NOT_FOUND: "QUOTE_NOT_FOUND",
  EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  // Business logic
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VEHICLE_ALREADY_SOLD: "VEHICLE_ALREADY_SOLD",
  VEHICLE_ARCHIVED: "VEHICLE_ARCHIVED",
  SALESPERSON_NOT_MEMBER: "SALESPERSON_NOT_MEMBER",
  ASSIGNED_USER_NOT_MEMBER: "ASSIGNED_USER_NOT_MEMBER",
  SALE_ALREADY_COMPLETED: "SALE_ALREADY_COMPLETED",
  PENDING_REQUEST_EXISTS: "PENDING_REQUEST_EXISTS",
  REQUEST_ALREADY_RESOLVED: "REQUEST_ALREADY_RESOLVED",
  OWNER_ROLE_LOCKED: "OWNER_ROLE_LOCKED",
  ROLE_IN_USE: "ROLE_IN_USE",
  ALREADY_MEMBER: "ALREADY_MEMBER",
  ALREADY_ADMIN: "ALREADY_ADMIN",
  CANNOT_REMOVE_OWNER: "CANNOT_REMOVE_OWNER",
  CANNOT_CHANGE_OWNER_ROLE: "CANNOT_CHANGE_OWNER_ROLE",
} as const;

export type AppErrorCode = typeof AppErrorCode[keyof typeof AppErrorCode];

export interface AppErrorData {
  code: AppErrorCode;
  message: string;
}

export function throwAppError(code: AppErrorCode, message: string): never {
  throw new ConvexError({ code, message });
}
