import { ConvexError } from "convex/values";

export const AppErrorCode = {
  // Auth
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  // Not found
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  SALE_NOT_FOUND: "SALE_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  LEAD_NOT_FOUND: "LEAD_NOT_FOUND",
  QUOTE_NOT_FOUND: "QUOTE_NOT_FOUND",
  EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  DEPOSIT_NOT_FOUND: "DEPOSIT_NOT_FOUND",
  // Business logic
  DEPOSIT_ALREADY_RESOLVED: "DEPOSIT_ALREADY_RESOLVED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VEHICLE_ALREADY_SOLD: "VEHICLE_ALREADY_SOLD",
  VEHICLE_ARCHIVED: "VEHICLE_ARCHIVED",
  SALESPERSON_NOT_MEMBER: "SALESPERSON_NOT_MEMBER",
  ASSIGNED_USER_NOT_MEMBER: "ASSIGNED_USER_NOT_MEMBER",
  SALE_ALREADY_COMPLETED: "SALE_ALREADY_COMPLETED",
  SALE_ALREADY_CANCELLED: "SALE_ALREADY_CANCELLED",
  PENDING_REQUEST_EXISTS: "PENDING_REQUEST_EXISTS",
  REQUEST_ALREADY_RESOLVED: "REQUEST_ALREADY_RESOLVED",
  OWNER_ROLE_LOCKED: "OWNER_ROLE_LOCKED",
  ROLE_IN_USE: "ROLE_IN_USE",
  ALREADY_MEMBER: "ALREADY_MEMBER",
  ALREADY_ADMIN: "ALREADY_ADMIN",
  CANNOT_REMOVE_OWNER: "CANNOT_REMOVE_OWNER",
  CANNOT_CHANGE_OWNER_ROLE: "CANNOT_CHANGE_OWNER_ROLE",
  // SCRUM-51. Claims is retired as an accounting authority; its five
  // writers refuse rather than open a second finance-company receivable.
  CLAIMS_RETIRED: "CLAIMS_RETIRED",
  // SCRUM-495. LEASE and INTERNAL_INSTALLMENT are no longer offered; every door
  // that would create or finalize a deal in one refuses with this code.
  DEAL_MODE_RETIRED: "DEAL_MODE_RETIRED",
  // SCRUM-239. Returning a cleared finance-company cheque from the deal; each
  // refusal is raised before the first write and is translated under
  // ServerError_<code>.
  FINANCE_RETURN_NOT_DISBURSED: "FINANCE_RETURN_NOT_DISBURSED",
  FINANCE_RETURN_CHEQUE_NOT_CLEARED: "FINANCE_RETURN_CHEQUE_NOT_CLEARED",
  FINANCE_RETURN_CHAIN_MISMATCH: "FINANCE_RETURN_CHAIN_MISMATCH",
  FINANCE_RETURN_ALLOCATION_SHAPE: "FINANCE_RETURN_ALLOCATION_SHAPE",
  FINANCE_RETURN_REVERSAL_UNPROVEN: "FINANCE_RETURN_REVERSAL_UNPROVEN",
  FINANCE_RETURN_REASON_REQUIRED: "FINANCE_RETURN_REASON_REQUIRED",
  FINANCE_RETURN_REASON_TOO_LONG: "FINANCE_RETURN_REASON_TOO_LONG",
  FINANCE_CHEQUE_RETURN_FROM_DEAL: "FINANCE_CHEQUE_RETURN_FROM_DEAL",
  // SCRUM-239 follow-up. One code for a missing and a foreign-organisation row,
  // so the refusal never discloses that another tenant's row exists.
  FINANCE_RETURN_NOT_FOUND: "FINANCE_RETURN_NOT_FOUND",
  FINANCE_RETURN_KEY_CONFLICT: "FINANCE_RETURN_KEY_CONFLICT",
  // `collections.returnCheque`: RETURNED is terminal for returning.
  CHEQUE_ALREADY_RETURNED: "CHEQUE_ALREADY_RETURNED",
  CHEQUE_NOT_RETURNABLE: "CHEQUE_NOT_RETURNABLE",
  CHEQUE_NOT_FOUND: "CHEQUE_NOT_FOUND",
  // SCRUM-239 round 2.
  CHEQUE_NOT_CLEARED: "CHEQUE_NOT_CLEARED",
  FINANCE_RETURN_KEY_INVALID: "FINANCE_RETURN_KEY_INVALID",
  FINANCE_CONFIRM_STALE_REQUEST: "FINANCE_CONFIRM_STALE_REQUEST",
} as const;

export type AppErrorCode = typeof AppErrorCode[keyof typeof AppErrorCode];

/**
 * The one structured `ConvexError` payload: a machine code plus the English
 * message `lib/errors.ts` `getErrorMessage` shows. A domain with its own code
 * vocabulary (e.g. the closing-readiness reasons, SCRUM-414) widens `C`
 * rather than defining another shape.
 */
export type AppErrorData<C extends string = AppErrorCode> = {
  code: C;
  message: string;
};

export function throwAppError(code: AppErrorCode, message: string): never {
  throw new ConvexError({ code, message });
}
